// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtkU2XvUCM5jtwe1GRDjQNTTbrP1a5cpI',
    appId: '1:921447527285:web:1cad3020a32fe68e6bd93c',
    messagingSenderId: '921447527285',
    projectId: 'cocodata-bab89',
    authDomain: 'cocodata-bab89.firebaseapp.com',
    databaseURL: 'https://cocodata-bab89-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cocodata-bab89.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBPsBBZDwB-lpLZr7wKHGkUbAMQ5xkjms',
    appId: '1:921447527285:android:9cf67ff7b300d1326bd93c',
    messagingSenderId: '921447527285',
    projectId: 'cocodata-bab89',
    databaseURL: 'https://cocodata-bab89-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cocodata-bab89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7fQFdG-ucs-702C5liDPy-PXta8AaAls',
    appId: '1:921447527285:ios:608c7278ed3822726bd93c',
    messagingSenderId: '921447527285',
    projectId: 'cocodata-bab89',
    databaseURL: 'https://cocodata-bab89-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cocodata-bab89.firebasestorage.app',
    iosBundleId: 'com.example.droneProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7fQFdG-ucs-702C5liDPy-PXta8AaAls',
    appId: '1:921447527285:ios:608c7278ed3822726bd93c',
    messagingSenderId: '921447527285',
    projectId: 'cocodata-bab89',
    databaseURL: 'https://cocodata-bab89-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cocodata-bab89.firebasestorage.app',
    iosBundleId: 'com.example.droneProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtkU2XvUCM5jtwe1GRDjQNTTbrP1a5cpI',
    appId: '1:921447527285:web:76b0c7174ef142496bd93c',
    messagingSenderId: '921447527285',
    projectId: 'cocodata-bab89',
    authDomain: 'cocodata-bab89.firebaseapp.com',
    databaseURL: 'https://cocodata-bab89-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cocodata-bab89.firebasestorage.app',
  );

}